apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dq5mjkcip-dotnet-basic
  janus-idp.io/tekton: dq5mjkcip-dotnet-basic
  backstage.io/kubernetes-id: dq5mjkcip-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dq5mjkcip-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
